### ISSUE TITLE
Remove the cloud function profile from http connectors

### ISSUE THREAD

**Issue by chillleader** [camunda/connectors#1038]
__What should we do?__

The cloud function profile is only used for REST connector proxy deployment. Since this configuration is SaaS-specific, we should consider moving it into an internal repository.

Alternatively, if we decide to keep it here, we should only keep it in the pom file of the REST Connector, and not other HTTP-based connectors.

__Why should we do it?__

To reduce complexity and only maintain the configurations that are actually used.

**Comment by bastiankoerber** [comment]
related to Maven profile

**Comment by mattli2024** [comment]
closed not relevant
