### ISSUE TITLE
[Inbound] Support more event types

### ISSUE THREAD

**Issue by chillleader** [camunda/connectors#1040]
__Is your feature request related to a problem? Please describe.__

Currently the Connector Runtime only supports 2 specific types of BPMN elements for inbound connectors:
- None StartEvent
- Message IntermediateCatchEvent

User feedback indicates that this is not enough and we need to support more event types:
- Message StartEvent
- Boundary Events
- Intermediate events in embedded subprocesses
- _...to be continued_

__Describe the solution you'd like__

Process XML parser code in the runtime is extended to consume more types of inbound events as listed above.

__Describe alternatives you've considered__

None

__Additional context__

related to: https://github.com/camunda/team-connectors/issues/406, https://github.com/camunda/team-connectors/issues/468

**Comment by bastiankoerber** [comment]
check if the scope is covered by https://github.com/camunda/product-hub/issues/1515 and close it afterwards
