### ISSUE TITLE
Append Operation in Google Sheet Connector

### ISSUE THREAD

**Issue by quentinleroy** [camunda/connectors#1047]
__Is your feature request related to a problem? Please describe.__

Today, the connector allows users to create a new row based on a fixed integer. This means that to add a new row in an existing sheet, the connector needs to know in which row the last data set was inserted. This adds logic (and complexity) to the model itself, which is unnecessary.

__Describe the solution you'd like__

The Google Sheet API provides a functionality that allows the user to insert a row at the bottom of an existing sheet, without the need of providing an exact row number. 
This would make it easier for users to log information (ie. variables) outside of Camunda and make them easily consumable by business users.  

__Describe alternatives you've considered__

I've been using Optimize instead to look at data, but it is not optimised to look at text, hence variables such as descriptions are not displayed as they should. 

__Additional context__

[Feature in Productboard with insights](https://camunda.productboard.com/feature-board/6990815-overview-board/features/22109426/detail)

**Comment by igpetrov** [comment]
Assigning to @bastiankoerber and @sbuettner to set proper priority
