### ISSUE TITLE
Bad Request with Google Sheet Connector

### ISSUE THREAD

**Issue by quentinleroy** [camunda/connectors#1048]
__Describe the Bug__

When a variable parsed into the value field contains more than one output, the values are not parsed correctly to the Google Sheet APi. Instead, the variables are nested together, which leads to an error.

Example payload that works: 
`{"spreadsheetId":"1X3cHTZk3qISEfnRmlhQscNMXLG3Bnu0n362PeLEenpA","values":["Id","Title","Description","connectors"],"type":"createRow","worksheetName":"New Notifications WIP","rowIndex":"3"}`

Example payload that DO NOT works:
`{"spreadsheetId":"1X3cHTZk3qISEfnRmlhQscNMXLG3Bnu0n362PeLEenpA","values":["Id","Title","Description",["console","connectors"]],"type":"createRow","worksheetName":"New Notifications WIP","rowIndex":"3"}`

__Steps to Reproduce__

1. Create a model with a start form that contains a list with multiple choices (ie Components: Console, Operate, Web Modeler, Connectors)

<img width="773" alt="Screenshot 2023-08-17 at 12 37 40" src="https://github.com/camunda/connectors/assets/24291958/17af959d-c7da-4c92-bff4-430450a1ac55">

2. Set up Google Sheet connector to "Create a Row"
3. Insert an array of variables in the value field, one of which should contain the variable attached to the list with multiple choices

<img width="384" alt="Screenshot 2023-08-17 at 12 39 44" src="https://github.com/camunda/connectors/assets/24291958/87b8228e-7a78-453a-8061-af7c0ecf81ec">

4. Deploy and Run the process by filling up the form and selecting multiple choices (ie. Connectors, Web Modeler)
5. Go to Operate and see the error

<img width="1439" alt="Screenshot 2023-08-17 at 12 27 16" src="https://github.com/camunda/connectors/assets/24291958/f311ae8a-06a3-468d-bc69-b6d84c6b168f">

__Expected Behavior__

The nested values should be inserted into the Google sheet without generating errors. 

__Environment__

- Camunda version: 8.2.0-alpha3

**Comment by igpetrov** [comment]
Assigning to @bastiankoerber and @sbuettner to set proper priority
