### ISSUE TITLE
Increase Maximum Length Value in Google Sheet Connectors

### ISSUE THREAD

**Issue by quentinleroy** [camunda/connectors#1049]
__Is your feature request related to a problem? Please describe.__

Today, the Google Sheet connector does not allow for more than 100 characters to be parsed. 

<img width="340" alt="Screenshot 2023-08-17 at 11 31 30" src="https://github.com/camunda/connectors/assets/24291958/46b7af58-c82c-4909-97c3-29412eb0e972">

When using FEEL expressions together with variable names, the number of characters can easily go over this limit; which in turn limit the number of use cases. 

__Describe the solution you'd like__

Optimally, we should not have a limit of the number of characters we can insert in this field, or have it much larger (ie. 5000)

__Describe alternatives you've considered__

The only work around today is not limit the amount of variables sent or change the names of those variables to be shorter. Both of those solutions degrade the user experience and the maount of use cases this connector provides. 

__Additional context__

See insight: https://camunda.productboard.com/insights/notes/view/1016-all-notes/notes/34959700

**Comment by ev-codes** [comment]
I'll work on the web-modeler PR next.

I'll first need to do some environment set-up on my machine, so that PR might not come for 1-2 days.
