### ISSUE TITLE
Postgres SQL Connector after a Rest Connector

### ISSUE THREAD

**Issue by altamash-k** [camunda/connectors#1063]
__Is your feature request related to a problem? Please describe.__

I want to have a process where in I want to make an api call through rest connector and then insert the response in my postgres sql connector

__Describe the solution you'd like__

I want to have a Postgres Connector that can be used to directly integrate in my process

__Describe alternatives you've considered__

One of the alternative that I used was using Infosys Postgres Connector, but it was not executing properly

**Comment by bastiankoerber** [comment]
hi @altamash-k , 
can you explain, why the Postgres Connector from infosys is not working?

**Comment by sbuettner** [comment]
@altamash-k we are closing this issue now. Feel free to comment in case of new information on this topic.
