### ISSUE TITLE
REST Connector to have custom groups

### ISSUE THREAD

**Issue by altamash-k** [camunda/connectors#1064]
__Is your feature request related to a problem? Please describe.__

I want to add a custom type of group in my rest connector, to either write FEEL scripts or embed external job workers

__Describe the solution you'd like__

Addition of a script/implementation group to play with the responses and further do some logic building in the connector itself

__Describe alternatives you've considered__

I tried playing with the properties of rest connector by changing the json code, but it was not able to add an extra group

**Comment by sbuettner** [comment]
Hi @altamash-k thank you for your request. Could you elaborate what you mean with custom group? Thank you!

**Comment by altamash-k** [comment]
Just like there are input, response mapping, err handling groups in a rest connector, I would like to have a custom type of group to embed or write scripts/logic

**Comment by sbuettner** [comment]
Hey @altamash-k, you can use the response of connectors / service tasks by using another task or a script task.
