### ISSUE TITLE
HTTP REST Connector: migrate from Google HTTP Connector

### ISSUE THREAD

**Issue by igpetrov** [camunda/connectors#1069]
__What should we do?__

Currently, HTTP REST and GraphQL connectors use Google HTTP Connector.

As a part of this task, we need to migrate to something more mature, such as Apache HTTP client, or other options to be considered.

__Why should we do it?__

As per [discussion](https://github.com/camunda/connectors/pull/1043#discussion_r1301448197), we agreed that it makes sense to do.

**Comment by sbuettner** [comment]
Relevant articles:
https://www.wiremock.io/post/java-http-client-comparison
https://www.innoq.com/en/articles/2022/01/java-http-clients/
https://reflectoring.io/comparison-of-java-http-clients/
