### ISSUE TITLE
Kafka Connector Template misconfigured to allow FEEL in Topic property 

### ISSUE THREAD

**Issue by NPDeehan** [camunda/connectors#1071]
__Describe the Bug__

The Kafka Connector Element template defines the `Topic` field as being able to accept a FEEL but the backend does not check for a FEEL expression in execution so it would end up taking whatever is written in there as a static value.

__Steps to Reproduce__

1. Build a process with a Start Event
2. Select the Kafka Connector from the connectors drop down.
3. Go to the topic field and see how the FEEL toggle is available
4. If a feel expression is added that field it will not be evaluated in runtime.

__Expected Behavior__

Feel expresssion should not be available as an option for that text box

- Camunda version: Camunda 8 SaaS

**Comment by sbuettner** [comment]
We will rather add FEEL support for the respective properties
