### ISSUE TITLE
Add "invoke workflow/action" operation to the OOTB GitHub Connector

### ISSUE THREAD

**Issue by tmetzke** [camunda/connectors#1074]
__Is your feature request related to a problem? Please describe.__

If I want to invoke a GitHub action or workflow from my C8 process, I have to manually put in all necessary data using the REST Connector. This is quite error-prone since I have to know all necessary headers and define the request body correctly.

__Describe the solution you'd like__

Using the GitHub connector, I would like to have the option to invoke an action/workflow.
I would want to input as little data as possible and as much custom data as required.

__Describe alternatives you've considered__

Use the REST Connector and define my own template once I figured out all the necessary headers and how to define the body correctly.

__Additional context__

API to run a workflow by dispatching a repository event: https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event

**Comment by bastiankoerber** [comment]
we really like your FR, but we are also open for contributions :-)
Do you have time for it? 
Otherwise we will move it to our backlog.

@tmetzke

**Comment by tmetzke** [comment]
@bastiankoerber, fine to have it moved to the backlog.
If we receive more requests, we might prioritize the feature in the future.
I probably won't have time to contribute that soon, I think.

**Comment by ev-codes** [comment]
I added the changes suggested in the QA process to #1634.

Once #1634 is merged, I'll:
- update the [web-modeler PR](https://github.com/camunda/web-modeler/pull/7703) and start the review process
- finalize the [camunda-docs PR](https://github.com/camunda/camunda-docs/pull/3206) and start the review process

**Comment by ev-codes** [comment]
I merged the [web-modeler PR](https://github.com/camunda/web-modeler/pull/7703), so this feature is ready for release.

I'll mark this issue as done.

After the next web-modeler release (likely within the next few weeks), I will request review for the [camunda-docs PR](https://github.com/camunda/camunda-docs/pull/3206).
