### ISSUE TITLE
Clarify that we need Operate to run Inbound connectors in our documentations

### ISSUE THREAD

**Issue by markfarkas-camunda** [camunda/connectors#1122]
__Is your feature request related to a problem? Please describe.__

Seems like it is not entirely clear for users that we need operate to run the inbound connectors.

See conversation: https://camunda.slack.com/archives/C02JLRNQQ05/p1693591828379519 
"Then, I wanted to run it using the docker image for the connector SDK. But, I faced two issues:
1/ It complains it needs a connection to OPERATE. This is not in the
documentation https://docs.camunda.io/docs/components/connectors/custom-built-connectors/connector-sdk/#docker-runtime-image"

__Describe the solution you'd like__

We should at least add the list of expected environment variables to https://docs.camunda.io/docs/components/connectors/custom-built-connectors/connector-sdk/#docker-runtime-image

```
- CAMUNDA_OPERATE_CLIENT_URL=http://operate:8080/
- CAMUNDA_OPERATE_CLIENT_USERNAME=demo
- CAMUNDA_OPERATE_CLIENT_PASSWORD=demo
```

We should also clarify why this is necessary, and in general why one need Operate to be able to run Inbound connectors.

**Comment by chillleader** [comment]
Addressed in https://github.com/camunda/camunda-platform-docs/pull/2612
