### ISSUE TITLE
Add possibility to retrieve job-related general purpose information from the context in a connector

### ISSUE THREAD

**Issue by itsmestefanjay** [camunda/connectors#1153]
__Is your feature request related to a problem? Please describe.__

I want to add certain general purpose information from a running process instance calling my connector into my logic, e.g. to distinguish a local file path for different process instances using my outbound connector I would like to receive the _processInstanceKey_ from the context or from a separate object.

__Describe the solution you'd like__

For _@JobWorker_ methods I can get the _ActivatedJob_ parameter in my method to get these kind of information. Something similar for a connector would be great. Either from the context or from a similar object as the ActivatedJob object in JobWorkers.

__Describe alternatives you've considered__

Alternatively, I could think of having these kind of general purpose variables available through FEEL, so I can at least set them from the outside.

__Additional context__

None

**Comment by sbuettner** [comment]
Thanks @itsmestefanjay for your request. We discussed this and will provide access to the `ActivatedJob` via the `OutboundConnectorContext`.

**Comment by itsmestefanjay** [comment]
That‘s great. Thanks @sbuettner

**Comment by itsmestefanjay** [comment]
@sbuettner Quick question, I added the 0.23.2 release into my connector but the changes you made are not available there. Did I miss something there?

**Comment by sbuettner** [comment]
All good @itsmestefanjay. The PR wasnt part of the patch release but will be included in the next official release (2023/10/10). For development purposes you could checkout the `main` branch and use the latest SDK (via `mvn install`) and use the example application (`io.camunda.connector.runtime.app.LocalConnectorRuntime`) to run against a local/SaaS cluster.
