### ISSUE TITLE
[Support] [Bug] Escaped characters incorrectly deserialize from Kafka topic

### ISSUE THREAD

**Issue by igpetrov** [camunda/connectors#1236]
__Describe the Bug__

It was identified by the `SUPPORT-18661` that escaped special characters may lead to broken JSON parsing. See ticket for more information.

__Steps to Reproduce__

1. Create any Kafka inbound connector assigned to a topic
2. Publish into the topic the following message with escaped character, e.g. `\"`

```
{
  "key": "test",
  "value": {
    "payload": {
      "foo": "a\"string"
    }
  }
}
```

__Expected Behavior__

Message parses correctly.

__Environment__

- Any

__Related To__
- [SUPPORT-20896](https://jira.camunda.com/browse/SUPPORT-20896)

**Comment by igpetrov** [comment]
@sbuettner @bastiankoerber needs to be groomed

**Comment by Vadimnick** [comment]
@markfarkas-camunda Hi, can you please tell me when the fix is. We look forward to being corrected.   🙏🙏🙏
