### ISSUE TITLE
[Feature request] BPMN error expression with variables

### ISSUE THREAD

**Issue by igpetrov** [camunda/connectors#1237]
__Is your feature request related to a problem? Please describe.__

As per [message](https://camunda.slack.com/archives/C02JLRNQQ05/p1696003847404829), it would be a nice addition to existing error handling, adding context variables.

__Proposal__

Could look smth like `bpmnError("IDENTIFY_CHECK_ERROR", "Checking for an existing identity release failed", {myVar1:myVal1, ...})`

```[tasklist]
### Tasks
- [ ] Add error variables support to the runtime
- [ ] Add documentation
```

**Comment by igpetrov** [comment]
@bastiankoerber needs to be groomed

**Comment by megglos** [comment]
Some more context, the use case I have is in the Zeebe release process:
![image](https://github.com/camunda/connectors/assets/209518/c2db86be-3dfd-4fdc-b6b7-9facaf194b1a)

There a REST connector checks whether an identity release with the same version as we release zeebe with exists. So a 404 is an expected outcome that I would like to map to a variable.

As of now the task will fail with an error though on a 404.

**Comment by sbuettner** [comment]
As discussed in the architecture session we want to support variables from `errorExpressions` and allow to set them via feel: https://github.com/camunda/connectors/blob/2ac276e81f696a34e7d12c24dd0a4adcee5c083e/connector-sdk/jackson-datatype-feel/src/main/java/io/camunda/connector/feel/FeelConnectorFunctionProvider.java#L36

To not break existing code please check whether operator overloading is supported to add a new function that accepts variables or whether we can simply add `variables` as an additional parameter.

Also a reminder that the variables have to be send to zeebe via the `throwError` command.

**Comment by sbuettner** [comment]
As of https://github.com/camunda/connectors/pull/1285 we now support the following construct in an error expression:

```
bpmnError("myCode","myMessage", myFEELVariables)
```

**Comment by megglos** [comment]
@sbuettner that will still fail the task, right? This FR was about, I might not want it to fail if e.g. a 404 on a rest connector is a valid non-error outcome? e.g.
```
if error.code = "404" then
 { identity_release_exists: false }
else
 bpmnError("IDENTIFY_CHECK_ERROR", "Checking for an existing identity release failed")
 ```

**Comment by megglos** [comment]
Just realized this part got lost from the slack message to this issue 🙈 let me know if that is worth another FR.

**Comment by sbuettner** [comment]
@megglos Wouldnt that now be easier by leveraging an error boundary event that contains the payload of the variables and make the logic explicit inside the bpmn?
