### ISSUE TITLE
[Bug] Webhook: JWK URL is not validated in the element template

### ISSUE THREAD

**Issue by chillleader** [camunda/connectors#1239]
__Describe the Bug__

JWK endpoint URL is not validated in the webhook connector template.

__Steps to Reproduce__

1. Link a webhook connector to any start or intermediate event
2. Select JWT auth
3. Enter arbitrary non-URL value into the JWK endpoint URL field
4. Ensure no error displayed

__Expected Behavior__

We should only allow valid URLs or secrets `^(http|https|{{secret.*}})`.

It is also highly likely that JWK endpoint URL must not be left empty (also not validated).

__Environment__

C8 SaaS 8.3

**Comment by markfarkas-camunda** [comment]
Since we just talked about removing this url pattern from the REST Connector in or weekly meeting, we should not validate the JWK url with a regex.
Not allowing empty value on the other hand makes sense. We expect to have a value for the jwk url in the backend code.
