### ISSUE TITLE
Webhook: do not throw NullPointerException when the correlation key is in wrong format

### ISSUE THREAD

**Issue by markfarkas-camunda** [camunda/connectors#1244]
__Describe the Bug__

If we define Correlation key (payload) in the wrong format, we get a 500 error message in response. This is wrong because of 2 reasons: 
1. It is not helpful at all, and makes it impossible to users to figure out what to fix and how. I know because I had the exact same issue, and spent an hour figuring out what is wrong. 
2. We get the 500 because we have a NullPointerException in the backend. We should handle the case when the correlation key is not in the right format.

__Steps to Reproduce__

1. Run the bpmn diagram below.
2. Observe the 500 error throwns by the REST connector

[WRONG_webhook-intermediate-event-secrets-test.bpmn.txt](https://github.com/camunda/connectors/files/12844775/WRONG_webhook-intermediate-event-secrets-test.bpmn.txt)

__Screens__

![image](https://github.com/camunda/connectors/assets/119574841/40eb78f0-3fbb-4e03-ab88-09cf54d29c02)

![image](https://github.com/camunda/connectors/assets/119574841/59c2212a-2a5f-4697-b4d7-3dd39a67bfb0)

__Expected Behavior__

We should not throw a NullPointerException on the backend for this configuration, and should send back more information about what went wrong to the client.

__Environment__

- SaaS (8.3.0)
- Self Managed: 
    - OS: Windows 11
    - Camunda version: 8.3.0

**Comment by sbuettner** [comment]
I agree, we should have a proper error code like `CORRELATION_KEY_EXPRESSION_FAILED` or similar.
