### ISSUE TITLE
Support verification field in Connectors

### ISSUE THREAD

**Issue by igpetrov** [camunda/connectors#1303]
__Is your feature request related to a problem? Please describe.__

This problem is applicable to many Connectors which have two-step verification process.

Say, Slack for example. When a user subscribes to even API, Slack sends verification message first that looks like this:

```
{
  "token": "Jhj5dZrVaK7ZwHHjRyZWjbDl",
  "challenge": "3eZbrw1aBm2rZgRNFdxV2595E9CY3gmdALWMmHkvFXO7tYXAYM8P",
  "type": "url_verification"
}
```

And after response is returned, in this case, `challenge`, events start streaming. Typical event may look like this:

```
{
   "token": "XXXXXXXX",
   "team_id": "XXXXXXXX",
   "api_app_id": "XXXXXXXX",
   "event": {
      "client_msg_id": "ffb7ded2-6f55-468d-926f-cad3195c8056",
      "type": "app_mention",
      "text": "<@XXXXXXXX> say hello",
      "user": "XXXXXXXX",
      "ts": "11111111.2222222",
      "blocks": [
         {
            "type": "rich_text",
            "block_id": "rarsi",
            "elements": [
               {
                  "type": "rich_text_section",
                  "elements": [
                     {
                        "type": "user",
                        "user_id": "XXXXXXXX"
                     },
                     {
                        "type": "text",
                        "text": " say hello"
                     }
                  ]
               }
            ]
         }
      ],
      "team": "XXXXXXXX",
      "thread_ts": "1687864866.335329",
      "parent_user_id": "XXXXXXXX",
      "channel": "XXXXXXXX",
      "event_ts": "1687866358.496959"
   },
   "type": "event_callback",
   "event_id": "XXXXXXXX",
   "event_time": 1687866358,
   "authorizations": [
      {
         "enterprise_id": null,
         "team_id": "XXXXXXXX",
         "user_id": "XXXXXXXX",
         "is_bot": true,
         "is_enterprise_install": false
      }
   ],
   "is_ext_shared_channel": false,
   "event_context": "XXXXXXXX"
}
```

The problem starts with intermediate catch event connectors, specifically when we define correlation keys.
If we set correlation key expression as `=request.body.event.text` then upon the first request (`url_verification`), expression will be evaluated as `null` hence returning error HTTP code 422 `Correlation key not resolved: =request.body.event.text`.

As a workaround, we could have used more complex sentence, like `=if request.body.event = null then "" else <your payload extraction>` however, we agreed that it is not great CX experience for no-code users.

__Describe the solution you'd like__

As a proposed solution, it is suggested to have a separate field used for validation use-cases only. The field has to be hidden and supporting expressions. Upon evaluating expression, it should immediately return desired result, for example in slack case,
`=if request.body.type = "url_verification" then {"challenge": request.body.challenge}`.

__Open suggestions__

- Can we reuse response body expression?
- HMAC/other security mechanisms support
- Should it be handled by common code or connector specific?
- How do we want to support headers, status codes?
- TBD

**Comment by igpetrov** [comment]
Adding to the next architecture session

**Comment by sbuettner** [comment]
```mermaid
sequenceDiagram
    participant client as WebHook Client
    participant crt as Connector Runtime
    participant c as Connector
    client->>crt:  Http POST /inbound/myWebhook
   crt->>c: Execute verification expression
   crt->>c: Execute activation
   crt->>c: Execute correlation
```

As discussed in the architecture session:
* Add a `verify(WebhookProcessingPayload payload)` method to the `WebhookConnectorExecutable`.
* Implement a default implemention for the `HttpWebhookExecutable` that supports a `verificationExpression`.
* The result of the newly added method should support: 
  * `body` (can be a String|Map)
  * `headers` as a Map 
  * `statusCode` as an Integer

**Comment by igpetrov** [comment]
Somehow getting `{"empty":false,"traversableAgain":true}`

Probably could be solved similar to https://github.com/camunda/connectors/pull/1026/files

**Comment by sbuettner** [comment]
@igpetrov Looks like something is mapped to optional.

**Comment by igpetrov** [comment]
@sbuettner in this case, it is scala map, I don't see optional here 🤔
