### ISSUE TITLE
Deadlink to http connector in Readme license section

### ISSUE THREAD

**Issue by rob2universe** [camunda/connectors#1349]
__Describe the Bug__

https://github.com/camunda/connectors/tree/main#license
contains dead link to
https://github.com/camunda/connectors/blob/main/connectors/http-json

__Steps to Reproduce__

follow link

__Expected Behavior__

Unclear. The link is in the Apache license section (meaning free also in production).

It seem like the link should now point to 
https://github.com/camunda/connectors/tree/main/connectors/http/rest

However, this component is not available under Apache license, but under Camunda Self-Managed Free Edition license or the Camunda Self-Managed Enterprise Edition only
https://github.com/camunda/connectors/blob/main/connectors/http/rest/LICENSE.txt

Is there still an http connector under Apache license? Does the link nee dto be fixed and moved to the other license section?

**Comment by sbuettner** [comment]
Fixed via https://github.com/camunda/connectors/pull/1343/commits/b1d0814b7e9856582b6e3a4b23e5eb71f3e52498 and https://github.com/camunda/connectors/pull/1343/commits/3678a3f9379dae769b971c99388d1f4d61789e3a and yes the http json connector is still licensed under Apache 2.0. It was an oversight during a refactoring.
