### ISSUE TITLE
Webhook Start Event Not Functioning in Camunda 8.3.x, SaaS

### ISSUE THREAD

**Issue by ikheraj17** [camunda/connectors#1373]
__Describe the Bug__

A customer is having issues utilizing a Webhook start element to kick off a process instance; the webhook does not return the expected response in 8.3.x but works fine without modifying the process diagram in 8.2.x.  I've attached a screenshot of the API calls made in Postman. 
![Screen Shot 2023-11-06 at 12 41 05 PM](https://github.com/camunda/connectors/assets/59032162/90f1c279-6ace-4305-a74f-92629c790e42)
Please find the process diagram at hand [here](https://drive.google.com/file/d/1azQA8IduMSby2kDn6ZEpeLt6R2yhjmr6/view?usp=sharing).

__Steps to Reproduce__

1) Download the BPMN file attached to this ticket and upload to Camunda 8 Web Modeler.

2) Deploy diagram to a 8.3.x Zeebe cluster.

3) Note that the 'Webhook' tab in the properties panel for the start element does not show an active webhook

4) Test the webhook and notice the absence of expected response

5) Repeat steps 2-4 with an 8.2.x. Zeebe cluster and note the response

__Expected Behavior__

The webhook should function properly in 8.3.x. and provide the expected response in Postman.

__Hints__

It seems that upon disabling the authentication and authorization tabs within the webhook element, the webhook functions in 8.3.x... Further testing needed.

__Environment__

- Camunda version: 8.3.0 SaaS

**Comment by chillleader** [comment]
Hi @ikheraj17, thank you for your report. This behavior is expected: in 8.3.0 the Webhook connector response doesn't have a body by default.

Instead, it is now possible to configure a custom response body. There's an example [here](https://docs.camunda.io/docs/components/connectors/use-connectors/inbound/#example-configuring-an-http-webhook) (see _8. Response body expression_).

**Comment by alexcorremans** [comment]
Hey @chillleader, since this looks like a breaking change for this customer, could this be added to the [update guide](https://docs.camunda.io/docs/self-managed/operational-guides/update-guide/820-to-830/) and the [announcements page](https://docs.camunda.io/docs/reference/announcements/)?

**Comment by chillleader** [comment]
The docs update is merged and will be released soon.
