### ISSUE TITLE
GitHub inbound webhook connectors suddenly stops working

### ISSUE THREAD

**Issue by MaxTru** [camunda/connectors#1387]
__Describe the Bug__

GitHub inbound webhook connectors suddenly stops working

__Steps to Reproduce__

1. We have a GitHub Inbound Connector running in C8 SaaS Prod 8.3.1 cluster (07.11.2023)
<img width="406" alt="Bildschirmfoto 2023-11-07 um 17 41 06" src="https://github.com/camunda/connectors/assets/42800119/10ff9df8-9bc5-4c88-9747-113c36984e89">
2. This Inbound Connectors was working just fine:
<img width="790" alt="Bildschirmfoto 2023-11-07 um 17 41 42" src="https://github.com/camunda/connectors/assets/42800119/87bd8216-cabf-4e1f-8b32-8416101e9c1c">
3. Then suddenly, without any redeployment, the Connector returns 504 and does not trigger any process instances anymore:
<img width="812" alt="Bildschirmfoto 2023-11-07 um 17 42 38" src="https://github.com/camunda/connectors/assets/42800119/e1482c95-5d7f-4346-a5c9-9a7bd91fa00e">

The 504 response is empty:
<img width="801" alt="Bildschirmfoto 2023-11-07 um 17 45 52" src="https://github.com/camunda/connectors/assets/42800119/d7ffb384-39da-4601-aaa0-ff0ed88a5b96">

The cluster-id is: 8da2f67e-88ab-4b38-9e39-52bb0ea4855f on bru-2

__Expected Behavior__

Github inbound connectors does not just break.

__Environment__

C8.3.1 Prod as of 07.11. (C8 Dogfooding env).

**Comment by MaxTru** [comment]
Update: suddenly the Connector started working again: 
<img width="826" alt="Bildschirmfoto 2023-11-07 um 17 44 46" src="https://github.com/camunda/connectors/assets/42800119/d0b38a6f-5710-4f7a-8805-a8c6bc1b8121">

**Comment by sbuettner** [comment]
Was this maybe infrastructure/network/cluster related issue after all?  If any component like zeebe/operate isnt available the runtime cant to much about it.

Curious as the Connectors runtime doesnt return 504.

**Comment by MaxTru** [comment]
I don't know. But should we not be able to (1) be alarmed about such cases, (2) find out from logs?

**Comment by sbuettner** [comment]
@MaxTru Was this a one time issue due to the cluster state or would you like to keep it open?
