### ISSUE TITLE
Add support to specify/configure TTL for messages correlated by connector

### ISSUE THREAD

**Issue by blondacz** [camunda/connectors#1406]
The current connector configuration/code does not support specifying TTL for a message.

This causes an issue when the correlation key is specified for a StartEvent, a second message with the same correlation key (but a different message-id)  is sent and the desired behavior is not to start another process once the current one finishes.

Simply allowing to configure/specify TTL for the message could eliminate this issue. Zeebe client allows such configuration and there are examples in the docs for this case.

**Comment by bastiankoerber** [comment]
let's discuss it in our architecture sync on tueday @sbuettner , @igpetrov

**Comment by chillleader** [comment]
We will discuss it next week. We currently see multiple options how we can expose the TTL (e.g. in the connector properties or in the runtime configuration).

Also we need to decide whether we want to make it visible in the element template by default, or rather a hidden feature supported by the runtime.

**Comment by bastiankoerber** [comment]
https://docs.camunda.io/docs/components/concepts/messages/

**Comment by sbuettner** [comment]
@chillleader Can this be considered done?
As well as https://github.com/camunda/team-connectors/issues/547?

**Comment by chillleader** [comment]
We are waiting for QA @sbuettner, I decided to keep it open for now as we don't have an epic for this issue where we could track the remaining activities

**Comment by chillleader** [comment]
Implemented in 8.6.0-alpha2.1

**Comment by akeller** [comment]
@sbuettner requested this be added to the release notes via https://github.com/camunda/camunda-docs/pull/3860.
