### ISSUE TITLE
`application.properties` from `connector-runtime-application` is not applied to the runtime bundles

### ISSUE THREAD

**Issue by chillleader** [camunda/connectors#1464]
__Describe the Bug__

The [default properties file](https://github.com/camunda/connectors/blob/main/connector-runtime/connector-runtime-application/src/main/resources/application.properties) is not utilized in the SaaS / SM connector runtime bundles. 

Because of this issue, essential settings such as the number of worker threads are not enabled for the runtime bundles.

We should make sure these settings are enabled for the bundles too.

__Steps to Reproduce__

1. Build the runtime bundle (e.g. `default-bundle`)
2. Run it and observe that the actual number of threads is 1, although it is set to 10 in the `application.properties`.

__Expected Behavior__

Settings should be applied to bundles as well.

__Environment__

- Camunda version: 8.3.1

**Comment by igpetrov** [comment]
Taking a look

**Comment by igpetrov** [comment]
Experimental solution https://github.com/camunda/connectors/pull/2312

Need to discuss at the architecture session

**Comment by igpetrov** [comment]
Fixed with https://github.com/camunda/connectors/pull/2330
