### ISSUE TITLE
Scala module 2.15.3 requires Jackson Databind version >= 2.15.0 and < 2.16.0

### ISSUE THREAD

**Issue by zxuanhong** [camunda/connectors#1542]
__Describe the Bug__
1. Connector cannot start.Error message：Scala module 2.15.3 requires Jackson Databind version >= 2.15.0 and < 2.16.0

__Environment__

- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0] 8.4.0-alpha1
- Camunda version: [e.g. 8.0.4 (self-managed)] 8.4

**Comment by chillleader** [comment]
Hey @zxuanhong, could you provide more details about your use case? I'm assuming you have a version conflict between the new version of the runtime and your connector implementation. It would be very helpful if you could check the Maven dependency tree and identify where the conflicting versions are coming from.

**Comment by zxuanhong** [comment]
@chillleader I upgraded the spring-boot-starter-camunda-connectors to version 8.4.0-alpha2 already working and I think this bug has been fixed. So I'm going to close this issue
