### ISSUE TITLE
Element template generator: Validate resulting element template

### ISSUE THREAD

**Issue by chillleader** [camunda/connectors#1560]
__Is your feature request related to a problem? Please describe.__

As a Connector developer, I might feel frustrated because the generated element template can be invalid if I made a mistake in configuration. The most error-prone part is property conditions and IDs they reference, because IDs can be adjusted separately from the condition.

__Describe the solution you'd like__

Maven plugin should validate the resulting template, e.g. it should report failure if some conditions are invalid (properties with referenced IDs do not exist).

__Describe alternatives you've considered__

None

**Comment by mattli2024** [comment]
discussed and decided to close
