### ISSUE TITLE
Upgrade project to Java 21

### ISSUE THREAD

**Issue by sbuettner** [camunda/connectors#1588]
__What should we do?__

We should update the Connectors project to make use of the Java Language version 21.

- [ ] Upgrade the Java language level to 21
- [ ] Upgrade the Docker files to make use of a Java 21 based Docker base image.

__Why should we do it?__

We depend on `spring-zeebe` and the `zeebe-java-client`. Both upgraded to Java 21 for their upcoming 8.4.x releases. The Connectors should therefore be upgraded to 21 as well.

**Comment by sbuettner** [comment]
Investigate how this change will impact backwards compatibility for Connector developers.

**Comment by sbuettner** [comment]
@chillleader Can we close this or do you see additional work needed?

**Comment by chillleader** [comment]
I think we can close this since we are using Java 21 starting from [this commit](https://github.com/camunda/connectors/pull/1599)
