### ISSUE TITLE
OpenAI Connector models are fixed and point to outdated versions

### ISSUE THREAD

**Issue by Prokopp** [camunda/connectors#1959]
## Issue

The OpenAI connector allow only the choice of _GPT-3.5 Turbo_ or _GPT-4_. That leads to two issues:

1. Impossible to pin model versions for reliable behaviour. These two are aliases and OpenAI changes what model they point to over time.
2. Multiple alternative and often newer and more performant models are unavailable to the connector user.

## Solution

Change Model field in `connectors/connectors/openai/element-templates/openai-connector.json` from a dropdown to a text field to allow any model input.

**Comment by bastiankoerber** [comment]
default should be a dropdown, but there should be an option to define a "custom" model

**Comment by bastiankoerber** [comment]
we should add as well a property to define the temperature

**Comment by Prokopp** [comment]
> we should add as well a property to define the temperature

Absolutely, ability to pin version ans set temperature would improve stability and reproducible results.
