### ISSUE TITLE
Set up CD for dev environment

### ISSUE THREAD

**Issue by chillleader** [camunda/connectors#205]
__What should we do?__

We want our dev environment to be constantly updated with the latest builds from the main branch. Additionally, we want to be able to deploy the ad-hoc images built from the feature branches.

- [x] Get in touch with the Console team and clarify how we can automatically update SaaS clusters
- [ ] Configure a GH Action to deploy the main branch continiously
- [ ] Configure a GH Action to deploy a custom branch
- [ ] Configure autodeploy for SaaS proxy function (dev+int)

__Based on informations we got from the console team here is what we can do__

1. Create a test Generation which uses the SNAPSHOT version of the bundle, and re-create(delete and create again) the clusters using this specific Generation to trigger the change on push to main. For this we can use the official [Console API](https://api.cloud.dev.ultrawombat.com/openapi/docs/#/) after acquiring the access token as described [here](https://docs.camunda.io/docs/apis-tools/console-api-reference/)
_Status_: console API seems working so far, theoretically we are good to go

2. Slightly better solution: add the action run number to the docker image tag (SNAPSHOT-${{ github.run_number }}) to have information about the current state, and update the test generation "manually"(there is no official api for it, so we have to figure out how to authenticate). Updating a generation automatically triggers an update in the underlying clusters.
_Status_: we have the M2M credentials to authenticate and update generation so we are good here as well

3. The best solution: Extend the 2nd solution with creating a new generation with the branch name in its name([see](https://console.cloud.ultrawombat.com/external/openapi/docs/#/default/CreateClone)) every time we push to a branch (or update it if already exists), create a test cluster for it ([see](https://api.cloud.ultrawombat.com/openapi/docs/#/default/CreateCluster))(only create if not exists, will be updated automatically otherwise). After merging the branch delete the cluster([see](https://api.cloud.ultrawombat.com/openapi/docs/#/default/DeleteCluster)) and also the generation in connection with this branch([see](https://console.cloud.ultrawombat.com/external/openapi/docs/#/default/DeleteGeneration)) when deleting the branch automatically. For this solution we would also need to create a docker image for the specific branch and rebuild that image after every single commit. 
_Status_: see 2. 

__Besides the above we should also__

Have a pre-defined hard-coded set of Generations(ids) which we can update with a connector-bundle docker image we specify as an input parameter.
Use GitHub matrix for this purpose.

__In the future__

For every push to a branch indicated with deploy-preview label: create Generation(or have dedicated for each person which we update) and create cluster with TTL(now possible).

__Why should we do it?__

This will save us a lot of time during our daily work. Besides, we will get an easy-to-access shared development environment.

__Also__

Consider doing [the task](https://github.com/camunda/connectors-bundle/issues/479) as well in scope of this one.

__Branch__
https://github.com/camunda/connectors-bundle/tree/205-set-up-CD-for-dev-environment

**Comment by igpetrov** [comment]
@markfarkas-camunda @Oleksiivanov - using this ticket.

**Comment by markfarkas-camunda** [comment]
As we discussed [in our weekly](https://github.com/camunda/team-connectors/issues/558#issuecomment-1833494779), we close this issue, since we will have a preview environment, which is sufficient for us now.
