### ISSUE TITLE
[FR] Status code support in response expression

### ISSUE THREAD

**Issue by igpetrov** [camunda/connectors#2060]
## About

A Connectors user requested a status code in the response expression: https://forum.camunda.io/t/webhook-connector-response-statuscode/50684/2.

**Comment by sbuettner** [comment]
As discussed in the architecture session, we will support a dedicated new property `responseExpression`:
```
{
  headers: {} 
  body: {}
  statusCode: 201
}
```

We will keep supporting the existing `responseBodyExpression` and will deprecate it at a later point in time.

**Comment by abdulazizali77** [comment]
@igpetrov id like to work on this

**Comment by igpetrov** [comment]
Hi @abdulazizali77 

Contributions are always welcome!

**Comment by igpetrov** [comment]
Hi @abdulazizali77 

Do you have an ETA for a PR?

**Comment by sbuettner** [comment]
https://github.com/camunda/team-connectors/issues/741
