### ISSUE TITLE
Add `Branches > Create repository branch` operation to the OOTB GitLab Connector

### ISSUE THREAD

**Issue by wollefitz** [camunda/connectors#2160]
__Is your feature request related to a problem? Please describe.__

If I want to open a GitLab repository branches within my C8 process, I have to manually put in all necessary data using the REST Connector to call https://docs.gitlab.com/ee/api/branches.html#create-repository-branch. This is quite error-prone since I have to know all necessary headers and define the request body correctly. 

__Describe the solution you'd like__

Using the GitLab connector, I would like to have the option to create a repository branch.
I would want to input as little data as possible and as much custom data as required.

__Describe alternatives you've considered__

Use the REST Connector and define my own template once I figured out all the necessary headers and how to define the body correctly.

__Additional context__

- API documentation: https://docs.gitlab.com/ee/api/branches.html#create-repository-branch

**Comment by sbuettner** [comment]
@wollefitz Are you working on this? As I see that its "Ready" in the Web-Modeler project? We would then track it as a reference ticket.

**Comment by wollefitz** [comment]
> @wollefitz Are you working on this? As I see that its "Ready" in the Web-Modeler project? We would then track it as a reference ticket.

Yes, I'll contribute this directly.
