### ISSUE TITLE
[REST] Revisit URL validation patterns

### ISSUE THREAD

**Issue by igpetrov** [camunda/connectors#2236]
As it was mentioned in [this comment](https://github.com/camunda/connectors/pull/2219#discussion_r1535282024), we can improve URL regex validation.

**Comment by bastiankoerber** [comment]
@igpetrov  please specify or close if it is a duplicate

**Comment by igpetrov** [comment]
Closing in favor of duplicate https://github.com/camunda/team-connectors/issues/712
