### ISSUE TITLE
[REST Connector] Support POSTing application-x-www-form-urlencoded Content-Type

### ISSUE THREAD

**Issue by upgradingdave** [camunda/connectors#2292]
__Is your feature request related to a problem? Please describe.__

I'm attempting to implement a custom connector to consume the [Unqork](https://developers.unqork.io/) api. The Unqork api expects `grant_type`, `username`, and `password` to be POSTED as Content-Type `x-www-form-urlencoded` in order to receive a bearer token. 

Currently, [this line](https://github.com/camunda/connectors/blob/165d915aea67dafacce5df1a2f7c27b4e01ec026/connectors/http/http-base/src/main/java/io/camunda/connector/http/base/services/HttpRequestMapper.java#L119) is hard coding `Content-Type` to `application/json`. Also, [this section](https://github.com/camunda/connectors/blob/165d915aea67dafacce5df1a2f7c27b4e01ec026/connectors/http/http-base/src/main/java/io/camunda/connector/http/base/services/HttpRequestMapper.java#L97) of the code needs to be updated slightly to pass the data in the correct format. 

__Describe the solution you'd like__

Ideally, I'd like to be able to set `Content-Type` in the Headers section of the Rest Connector like so: 

```
{
  "Content-Type": "application/x-www-form-urlencoded"
}
```
And then pass in form fields in the body like this: 

```
{
  "grant_type":"password",
  "username":unqorkUsername,
  "password":unqorkPassword
}
```

![Screen Shot 2024-04-02 at 5 57 55 PM](https://github.com/camunda/connectors/assets/939229/bf797d49-1b17-404f-93a5-6180f97b337b)

__Describe alternatives you've considered__

I'd have to fork and maintain a separate branch to support this Unqork api. 

__Additional context__

Here's a PR: #2291

**Comment by johnBgood** [comment]
@sbuettner yes it is

**Comment by sbuettner** [comment]
@upgradingdave You should be good when using the latest alpha (`8.6.0-alpha3`).
