### ISSUE TITLE
Errors documentation links to non-existing URL

### ISSUE THREAD

**Issue by nikku** [camunda/connectors#2316]
__Describe the Bug__

In the SNS outbound connector I follow the link in the error handling documentation, leading to [this url](https://docs.camunda.io/docs/components/connectors/use-connectors/#bpmn-errors), a broken page anchor.

__Steps to Reproduce__

1. Create SNS outbound connector
2. Select it and check error handling documentation (cf. screen below :arrow_down:)

__Expected Behavior__

Error documentation link sends me to respective page anchor where I can learn more (including a picture to pick me up). Likely just [this](https://docs.camunda.io/docs/components/connectors/use-connectors/#error-expression).

__Environment__

- OS: Linux
- Library version: Any (Camunda Desktop Modeler v5.22.0)
- Camunda version: Camunda 8.5 (self-managed or SaaS)

----

![image](https://github.com/camunda/connectors/assets/58601/c18719a5-0f4d-43a5-9a6d-9d1af101a07f)

**Comment by nikku** [comment]
Could apply to additional connectors; did not check. 

As additional context the core properties panel UI moves away from descriptions, to tooltips, cf. https://github.com/camunda/example-data-properties-provider/issues/18.

**Comment by igpetrov** [comment]
SNS fixed some time ago already: we moved it from manual generation to automatic one. Found some element template versions with broken link and fixed them in batch here: https://github.com/camunda/web-modeler/pull/9015
