### ISSUE TITLE
Change our Docker base image

### ISSUE THREAD

**Issue by markfarkas-camunda** [camunda/connectors#2338]
## Low prio

__What should we do?__

We should change out docker base image to [21.0.2_13-jre-alpine](https://hub.docker.com/layers/library/eclipse-temurin/21.0.2_13-jre-alpine/images/sha256-efdec7ae2b3e60bb253cdbe046249ddc07f3f0056837658616a94097f22a7449?context=explore) We can take a look at how web-modeler team does it.

__Why should we do it?__

To have a slimmer docker image, which seems to have less vulnerabilities.

__Why don't we have this already?__

We get `#10 0.281 /bin/sh: useradd: not found` error when trying to build the image, so user management adjustments are necessary.

__References__

https://camunda.slack.com/archives/C0350959WG1/p1713945828541659

**Comment by sbuettner** [comment]
@markfarkas-camunda Did you already work in this?
