### ISSUE TITLE
[REST] Add Custom Authentication to REST connector

### ISSUE THREAD

**Issue by Oleksiivanov** [camunda/connectors#244]
__Is your feature request related to a problem? Please describe.__

https://github.com/camunda/team-connectors/issues/241#issuecomment-1403596306

__Describe the solution you'd like__

Add `Custom Authentication ` to HTTP-JSON connector.
- `Custom Authentication`  must contain `body` and `headers` as an optional field in the back-end part, and will be configured in a template for needed connector
- using `Custom Authentication`  I except the next action in the back-end part : 
      - get access token
      - execute a request, using the access token

This way same as OAuth2 authentication, only in `Custom Authentication` will optional fields.
Related 
https://github.com/camunda/team-connectors/issues/241

**Comment by bastiankoerber** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> [camunda/team-connectors#241 (comment)](https://github.com/camunda/team-connectors/issues/241#issuecomment-1403596306)
> 
> **Describe the solution you'd like**
> 
> Add `Custom Authentication ` to HTTP-JSON connector.
> 
> * `Custom Authentication` will not displaying in REST connector template, it need only for new connector wich reuse REST connector
> * `Custom Authentication`  must contain `body` and `headers` as an optional field in the back-end part, and will be configured in a template for needed connector
> * using `Custom Authentication`  I except the next action in the back-end part :
>   - get access token
>   - execute a request, using the access token
> 
> This way same as OAuth2 authentication, only in `Custom Authentication` will optional fields. Related [camunda/team-connectors#241](https://github.com/camunda/team-connectors/issues/241)

why do we not show it in our REst Connector template. We should add it there as well, since this is a missing functionality
