### ISSUE TITLE
[REST connector] Access response in error expression with status code 400  

### ISSUE THREAD

**Issue by saig0** [camunda/connectors#2520]
__Is your feature request related to a problem? Please describe.__

I use the [SpaceTraders connector](https://marketplace.camunda.com/en-US/apps/420889/spacetraders-sdk) in my process and try to access the response in the error expression. The connector is based on Camunda's REST connector. 

I followed the documentation for error expressions ([ref](https://docs.camunda.io/docs/components/connectors/use-connectors/#bpmn-errors-and-failing-jobs)) but I can't access the response if the API returned a status code `400`. 

In my case, the API returns a status code `400` and sends additional data about the failure:
  
```
// status code
400 Bad Request

// URL
POST https://api.spacetraders.io/v2/my/ships/C_4979-1/navigate

// response data
{
   "error":{
      "message":"Ship action failed. Ship is not currently in orbit at X1-ZQ60-A1.",
      "code":4236,
      "data":{
         "waypointSymbol":"X1-ZQ60-A1"
      }
   }
}
```

NOTE: This is specific for a failure response (i.e. status code `4xx`). If the response returns successfully (i.e. status code `2xx`), I can access the response data in the error expression.    

__Describe the solution you'd like__

I can access the response data in the error expression, even if the response has a status code `400`.

I can use the following error expression to throw a BPMN error if the error code in the response matches:

```
if matches(error.code, "4\d\d") and response.body.error.code = 4236 
then bpmnError("shipNotInOrbitError", response.body.error.message, response.body.error.data)
else null
```

__Describe alternatives you've considered__

None. Since the response has a status code `400`, I can't handle the response in the connector or the process.

__Additional context__

How to reproduce:
1. Deploy the process [Handle BPMN error.bpmn](https://github.com/camunda/connectors/files/15305252/Handle.BPMN.error.bpmn.txt) _(with .bpmn file extension)_
2. Create a new instance of the process
3. Wait and verify that the process instance has an incident at the last task

![Screenshot from 2024-05-14 10-10-26](https://github.com/camunda/connectors/assets/4305769/0f122619-cf32-4da2-8b36-151f1aba619d)

![Screenshot from 2024-05-14 10-11-15](https://github.com/camunda/connectors/assets/4305769/32a9ad3a-5788-49a0-b254-4441c62c00dd)

**Comment by johnBgood** [comment]
@saig0 Thank you for reporting this.
Something we can do short term is provide the **response** (if any) in the `error.errorVariables` object.

You would then be able to use the following error expression:
```
if matches(error.code, "4\d\d") and error.errorVariables.response.error.code = 4236 
then bpmnError("shipNotInOrbitError", error.errorVariables.response.error.message, error.errorVariables.response.error.data)
else null
```

**Comment by sbuettner** [comment]
@johnBgood Can we change the property name to `variables` to not repeat the `error` prefix here?

**Comment by johnBgood** [comment]
@sbuettner It's not been release if I'm correct, so yes let's change the name 👍

**Comment by saig0** [comment]
@johnBgood sounds interesting. :+1: 

Why do we plan to store the response in `error.variables.response.x` instead of `response.body.x`?

In other cases, I can access the response directly via `response.body.x`. Using a different prefix `error.variables.response.x` could be more complicated and confusing for users.

**Comment by johnBgood** [comment]
@saig0 good question :D 

The idea is that the solution explained above is pretty much free to implement + it solves the user need.

Then, we can collect users' feedback, if they're happy great. If not we can iterate and go for the more complex solution. 
Using `response.body.x` is more complex and it would require some specific code both in the Webhook Connector and the ConnectorJobHandler which is the core piece for Outbound Connectors. 

It's possible but longer and trickier :) (but we might implement it some day)

**Comment by saig0** [comment]
@johnBgood thank you for the reasoning. :+1: 

I care about the UX and vote for an intuitive solution that is aligned with the other expressions. If it is a general behavior that connectors store the error details in `error.variables`, it's fine.

I don't need a solution very soon. :wink:

**Comment by b3rnh8rd** [comment]
Is there already a plan for when these features will be available? Our project uses the REST connectors quite frequently. In many cases, the response would also be essential for correct processing in the event of an error.
