### ISSUE TITLE
RabbitMQ Connector does unnecessary message unsescape action.

### ISSUE THREAD

**Issue by Zapolski** [camunda/connectors#2730]
__Describe the Bug__

I use out-of-the-box RabbitMQ Connector. Message for sending contains string fields with escaped symbols, like:

```
{
   "data": {
       "company": "LTD \"Three bears\""
   }
}
```

Connector sends my message but consumer receives wrong message and fells with MessageConversionException. There’s a message which consumer receives:

```
{
   "data": {
       "company": "LTD "Three bears""
   }
}
```

All symbols `"\"` disappeared. Connector’s source code contains logic with unescaping json.

__Steps to Reproduce__

1. Prepare message object for sending by RabbitMQ connector. Object must contain field with escaped symbols. For example:
```
{
   "data": {
       "company": "LTD \"Three bears\""
   }
}
```
2. Use RabbitMQ connector for sending message.

__Expected Behavior__

I expect the same message in my RabbitMQ CONSUMER, message should be without any transformation.

__Environment__

- OS: [Linux Ubuntu]
- Library version: [RabbitMQ Connector io.camunda.connectors.RabbitMQ.v1 version 5]
- Camunda version: [e.g. 8.4. (self-managed)]

[Camunda 8 forum topic](https://forum.camunda.io/t/rabbitmq-connector-unescape-json-inside-connector/52937)

**Comment by sbuettner** [comment]
As discussed in our team meeting we will remove unnecessary unescaping from Connectors in the next alpha.

**Comment by mathias-vandaele** [comment]
After testing, removing `.map(StringEscapeUtils::unescapeJson)` `L65 io.camunda.connector.rabbitmq.outbound.MessageUtil` corrects the issue. 
I am not so sure about removing it as it might have been added for a valid reason, any thoughts @sbuettner  ?

**Comment by johnBgood** [comment]
I'm posting the forum comment I made here for visibility:

> It is due to [Zeebe escaping characters](https://github.com/camunda/camunda/issues/9859).
> Looking at this ticket, it seems that it might be resolved. If so, we will remove the unescapes in our connectors.

The way I see it, we might remove any unescaping (not only in the RabbitMQ connector), but let's wait for @sbuettner or @chillleader opinions.

**Comment by chillleader** [comment]
Right, that Zeebe issue was the reason we added it there. If the escaping issues are gone, we no longer need the workaround.

**Comment by mathias-vandaele** [comment]
@chillleader Should I make an update and modify it in every connector ?

**Comment by chillleader** [comment]
Yes please - although I imagine there might be some corner cases where we might decide to keep unescaping for certain reasons (or maybe not, let's see 🙂). But in general I think we should remove it from all connectors now.

**Comment by sbuettner** [comment]
Yes, lets remove unnecessary escaping it but not backport it as previous zeebe releases faced this issue.

**Comment by chillleader** [comment]
We reproduced this issue again for RabbitMQ inbound connector in 8.5 and need to do a partial backport. We shouldn't include the changes that fix this for the outbound connector due to a pre-existing Zeebe issue, but we can safely backport the part where the inbound connector deserializes the payload.
