### ISSUE TITLE
Create a script to generate an unique element template file

### ISSUE THREAD

**Issue by mathias-vandaele** [camunda/connectors#2947]
__Is your feature request related to a problem? Please describe.__

Write a CLI application that will generate an unique element template file.

__Describe the solution you'd like__

It will crawl through all git history of our repository (starting from main) and generate links to the raw element template.
Each different version of ET should have a link.

Then a file centralizing all those links will be generated:

Example:

```
{
   "iocamundaconnectorsinboundKafkaIntermediatev1":[
      {
         "version":1,
         "reference":"https://github/rawreference"
      },
      {
         "version":2,
         "reference":"https://github/rawreference"
      }
   ]
}
```

__Describe alternatives you've considered__

None

__Additional context__

**Comment by sbuettner** [comment]
@markfarkas-camunda to reach out to web-modeler team:
- Would you be fine with an connectors element template NPM dependency that you can integrate which contains plain json file(s) to be consumed.
