### ISSUE TITLE
http-json connector retries should be configurable or set to 1

### ISSUE THREAD

**Issue by McAlm** [camunda/connectors#297]
__Is your feature request related to a problem? Please describe.__

When a rest endpoint is not accessible or throws an error the connector tries three times in a row until an incident is being created. In most cases this is not needed, so the incident should be created right after the first failing try. There should be an option to override the retry value, if needed.

__Describe the solution you'd like__

Provide a configurable retry on the connector and the belonging template.

**Comment by chillleader** [comment]
Valid suggestion, moving this to backlog and will discuss in the nearest team meeting.

Closely related issue: https://github.com/camunda/team-connectors/issues/326

**Comment by bastiankoerber** [comment]
@chillleader this will be solved with the coming release, right?

**Comment by chillleader** [comment]
@bastiankoerber This is already possible in custom element templates by adding a custom property like this:
```
{
  "label": "Retries",
  "type": "Text",
  "value": "1",
  "binding": {
    "type": "zeebe:taskDefinition:retries"
  }
}
```
Then it will be visible in the element template and can be configured.

As for the custom element templates, we haven't added this property yet but planning to do so by the next release. I have created a task for this: https://github.com/camunda/connectors/issues/1007

**Comment by bastiankoerber** [comment]
this is possible, see comments. Follow up ticket was created (update all our templates)

**Comment by sbuettner** [comment]
Relates to https://github.com/camunda/product-hub/issues/1382
