### ISSUE TITLE
German special chars cause timeout in ChatGPT / http-connector

### ISSUE THREAD

**Issue by ThomasGuett** [camunda/connectors#3078]
__Describe the Bug__

Using special chars like "äüöß" in prompts causes time out errors. 

__Steps to Reproduce__

1. use OpenAI ChatGPT Connector in a process
2. select "chat"
3. place a german prompt including any of the german special chars "äöüß"
4. start process
5. wait for time-out

__Expected Behavior__

expected same immediate response as if using pure english requests, or same german text, but without these special chars.

__Environment__

- C8 SaaS
- out-of-the-box OpenAI (ChatGPT) Connector

**Comment by sbuettner** [comment]
Hey @ThomasGuett I just tried it in our `int` environment and I dont see this issue happening. What environment are you running this in?

<img width="404" alt="Bildschirmfoto 2024-08-12 um 13 17 12" src="https://github.com/user-attachments/assets/f3b067a6-0ac6-406c-8f9c-6d43eabe049d">

**Comment by ThomasGuett** [comment]
Hey @sbuettner , sorry for the late reply. I'm experiencing this issue in the SaaS environment at bru-2 with Connectors 8.5.5.

**Comment by sbuettner** [comment]
@ThomasGuett We haven faced or seen this issue. Is it reproducible on your side? If so please re-open this issue. Thanks!
