### ISSUE TITLE
Update template descriptions and add keywords to improve refactorings suggestions

### ISSUE THREAD

**Issue by philippfromme** [camunda/connectors#3089]
__What should we do?__

The ✨ feature for selected elements in Web Modeler suggests connectors based on an element's name. The suggestions are based on the name and description of the connector templates and therefore the quality of suggestions depends on those.

![image](https://github.com/user-attachments/assets/db063346-cb9c-4628-ba8e-0ea83a504e12)

The latest version of the ✨ also takes into account keywords that were added to a template. For example, the following template

```json
{
  "$schema": "https://unpkg.com/@camunda/zeebe-element-templates-json-schema/resources/schema.json",
  "name": "Twitter Connector",
  "id": "io.camunda.connectors.Twitter",
  "version": 1,
  "description": "Post and manage tweets on Twitter",
  "metadata": {
    "keywords": [
      "create tweet",
      "delete tweet",
      "quote tweet",
      "reply to tweet",
      "retweet"
    ]
  },
  "category": {
    "id": "connectors",
    "name": "Connectors"
  },
  "appliesTo": [
    "bpmn:Task"
  ],
  "properties": []
}
```

has a `keywords` field with relevant keywords. If an element's name mentions replying to a tweet the connector will be suggested based on the matching keyword.

__Why should we do it?__

To improve the quality of suggestions.

Related to https://github.com/bpmn-io/refactorings/pull/27

**Comment by philippfromme** [comment]
@chillleader @Oleksiivanov  @igpetrov What is the source of truth for element template descriptions? I couldn't find anything other than the templates themselves?

**Comment by YanaSegal** [comment]
@philippfromme depends where:
- append element description is from the template
- browse marketplace coming from the marketplace page

**Comment by philippfromme** [comment]
Yes, I'm talking about the templates themselves. But since they are generated I was wondering where the descriptions are coming from and who is responsible for them.

**Comment by YanaSegal** [comment]
The template creator is responsible for providing the description.

**Comment by crobbins215** [comment]
@johnBgood is this something you could pick up and discuss with @philippfromme? @philippfromme is happy to help and hopefully, this would be a quick pick to get done, it's going to improve the connector suggestions.

**Comment by johnBgood** [comment]
@philippfromme It's generated using the Element Template Generator (ETG). The ETG parse our Java models and generates the json files.
Each Outbound Connector extends `OutboundConnectorFunction`, for instance the [SQL Connector](https://github.com/camunda/connectors/blob/main/connectors/jdbc/src/main/java/io/camunda/connector/jdbc/outbound/JdbcFunction.java#L38). In this file you will find a property named `inputDataClass` which points the Data class (JdbcRequest in this case).
You can then check the different properties, and will find a `description` property (not always though).

For instance in the [JdbcRequestData](https://github.com/camunda/connectors/blob/995e21ddd1633fe74a31ebbed830ec1f59ff3b60/connectors/jdbc/src/main/java/io/camunda/connector/jdbc/model/request/JdbcRequestData.java#L14-L25) record.

Please let me know if it's clear enough, I'm happy to discuss it more.

**Comment by philippfromme** [comment]
Okay, I finally found what I was looking for. The descriptions are in the source files: https://github.com/search?q=repo%3Acamunda%2Fconnectors%20description%20%3D&type=code. For example: https://github.com/camunda/connectors/blob/fcc8705b7f329b9667218b76104aef83ec8968b3/connectors/jdbc/src/main/java/io/camunda/connector/jdbc/outbound/JdbcFunction.java#L26

And to add the new `keywords` property can I just add it to the source files or does it need to be supported by the meta model first?

**Comment by philippfromme** [comment]
@johnBgood Sorry, I did actually see your message and based on it I was able to find what I was looking for, so thank you. 😃

**Comment by philippfromme** [comment]
@johnBgood Would it look something like [this](https://github.com/camunda/connectors/pull/3466)?

**Comment by philippfromme** [comment]
@johnBgood Thanks for helping out with that!

**Comment by philippfromme** [comment]
@johnBgood For connectors like the [Asana connector](https://github.com/camunda/connectors/blob/main/connectors/asana/element-templates/asana-connector.json) there seems to be a template only. Are these not generated and therefore have to be modified directly?

**Comment by johnBgood** [comment]
@philippfromme exactly, some connectors are based on other connectors (the REST connector in this case).

You can see it looking at these lines:

```json
 {
      "type": "Hidden",
      "value": "io.camunda:http-json:1",
      "binding": {
        "type": "zeebe:taskDefinition",
        "property": "type"
      }
    },
```

http-json:1 is the REST Connector.

Just putting this here for context, you're right you need to update the JSON file directly for these connectors.

**Comment by johnBgood** [comment]
@philippfromme If there are Java files, then the JSON will be generated. But only in our repo.
The web modeler part needs to be updated manually :/ 

So yea, in this example you need to update: 
- The Java files  + then generate the JSON templates using `mvn clean install -DskipTests` 
- The web modeler part

**Comment by philippfromme** [comment]
> The web modeler part

**Comment by johnBgood** [comment]
> But this going to change soon if I'm not mistaken

True :)
