### ISSUE TITLE
RabbitMQ connector should be able to process JSON messages with escape characters

### ISSUE THREAD

**Issue by chillleader** [camunda/connectors#3109]
__Describe the Bug__

The RabbitMQ connector doesn't attempt unescaping the message content. It would be useful

__Steps to Reproduce__

1. Produce a message with escape characters (e.g. `{\"hello\": \"world\"}`)
2. Configure the correlation key expression to extract something from the escaped payload, e.g. `=message.body.hello`
3. Make sure the message is rejected as the connector is unable to parse escaped data

__Expected Behavior__

The connector can parse escaped JSON

__Environment__

- Connectors version: 8.5, other versions are also affected

**Comment by crobbins215** [comment]
@chillleader is going to request more information from the customer

**Comment by chillleader** [comment]
See update here: https://github.com/camunda/connectors/issues/2730#issuecomment-2296518574
