### ISSUE TITLE
Webhook Start Event: POST request body not included in webhook response (8.5.6)

### ISSUE THREAD

**Issue by ev-codes** [camunda/connectors#3198]
__Describe the Bug__

POST request body is not included starting in Connectors 8.5.6. In 8.5.5, this works as expected.

__Steps to Reproduce__

1. Create a BPMN with a Webhook Start Event Connector with POST method and that saves result to a process variable (or use the [example here](https://github.com/user-attachments/files/16794503/webhook-start-post.bpmn.txt))
2. Deploy the BPMN
3. Trigger the webhook using a POST request with a non-empty body
4. The result process variable does not contain the body

[webhook-start-post.bpmn.txt](https://github.com/user-attachments/files/16794503/webhook-start-post.bpmn.txt)

__Expected Behavior__

The body from the request in step 3 should appear in the process variable from step 4.

__Environment__

- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]
- Camunda version: 8.5.6

**Comment by johnBgood** [comment]
This was not a bug, but the full discussion is [here](https://camunda.slack.com/archives/C02JLRNQQ05/p1724194035422699).

> They're using the latest version of the Webhook connector template (version 11), and they probably use a Connectors Runtime version < 8.6. There's an incompatibility for the responseExpression field.
Old runtimes (<8.6) expect a responseBodyExpression field and 8.6 expects responseExpression (which is contained in the template you provided, in version 11).
:checked: 2 solutions
You change the template version to 10 manually as shown in the video I posted
You use a Connectors Runtime 8.6.x
Hope that helps!
