### ISSUE TITLE
Proxy Exception List for Outbound HTTP Connectors

### ISSUE THREAD

**Issue by shaarmann** [camunda/connectors#3252]
__Is your feature request related to a problem? Please describe.__

May companies have private and use public APIs. Private APIs must be accessed via a proxy while public ones must not. The HTTP Connectors have not option to turn the proxy on/off via configuration nor can a list of exceptions be provided.

__Describe the solution you'd like__

Option 1:
Add a flag to the HTTP Connectors element templates. The request will be routed to proxy if and only if the flag is set to true.

Option 2:
The Proxy can be configured via an environment variable (HTTP_PROXY_URL). Another Environment variable may be used to specify exceptions, similiar to [Java's `http.nonProxyHosts`](https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html).

__Describe alternatives you've considered__

Use the hybrid mode of the connectors to run two instances of the HTTP Connectors: One with configured Proxy, one without.

__Additional context__

- Slack Discussion: https://camunda.slack.com/archives/C02JLRNQQ05/p1725282139313859

**Comment by sbuettner** [comment]
Decision: Go with Option 2 for now to now confuse SaaS users with this flag (as they will always go through a proxy.)

**Comment by shaarmann** [comment]
As mentioned in the ticket's description, their are JVM options for setting a proxy, i.e.,
```
http[s].proxyHost
http[s].proxyPort
http[s].nonProxyHosts
http[s].proxyUser
http[s].proxyPassword
```
Customers familiar with Java are used to these properties.
Therefore, I believe it is worth evaluating whether it is possible  to use these configuration options instead of custom environment variables. It has the additional benefit that functionality, such as `nonProxyHosts` and authentication are supported out-of-the-box.

Since version 8.6, the HTTP connector is based on Apache HTTP Client. Since version 5, the [HTTPClientBuilder](https://hc.apache.org/httpcomponents-client-5.3.x/current/httpclient5/apidocs/) uses the system properties described above, if no other proxy configuration is set.
The connector, however, [always sets a proxy configuration](https://github.com/camunda/connectors/blob/main/connectors/http/http-base/src/main/java/io/camunda/connector/http/base/client/apache/CustomApacheHttpClient.java#L107) -- even if it null. Thereby, it overwrites the default configuration. If we change the code to only set the proxy if it is configured via the environment variable above, it will fallback to the system configuration which supports the desired feature.

**Comment by johnBgood** [comment]
# QA information

## Test Environment
- Self-Managed only
- Connectors version: camunda/connectors-bundle:SNAPSHOT
- Beeceptor:
  - use the Camunda domain for the test
  - use another domain [as a proxy that forward requests](https://beeceptor.com/docs/forward-proxy-with-mock/#configuring-proxy) to the Camunda domain.

## Test Scope

- Docs TODO!
- Test that:
  - requests that should use a proxy are sent to the proxy domain
  - requests with a host contained in the proxy exception list go don't go through the proxy domain


## Test Data

You will need to provide the `JAVA_OPTS` env var:
```yaml
services:
  connectors:
    environment:
      - JAVA_OPTS=-Dhttp.proxyHost=<PROXY> -Dhttp.proxyPort=<PORT> -Dhttps.proxyHost=<PROXY> -Dhttps.proxyPort=<PORT> -Dhttp.nonProxyHosts=<OTHER_DOMAIN>
```

Replace the variables accordingly.

**Comment by slolatte** [comment]
@Szik and I tested this and everything looks good to us!
