### ISSUE TITLE
Adding a Reply To field when sending emails in Email connector

### ISSUE THREAD

**Issue by superbeagle** [camunda/connectors#3571]
__Is your feature request related to a problem? Please describe.__

As a developer, I would like to be able to set the Reply To address separately from the From email address when sending emails

__Describe the solution you'd like__

An added field in the connector template to collect the Reply To address when needed. In many instances the reply to is the sender but in some cases a developer wants to send a reply to another email address.

__Describe alternatives you've considered__

__Additional context__

**Comment by superbeagle** [comment]
In looking at the code I might be able to create a Pull request for this if I have time :)

**Comment by sbuettner** [comment]
@superbeagle We discssed this in the grooming and would like to offer this via custom header support. Would that work for you?

**Comment by superbeagle** [comment]
@sbuettner that would work! It's not a common use case but one that might come up from time to time
