### ISSUE TITLE
Starting webhook connector correlation key

### ISSUE THREAD

**Issue by jjettenCamunda** [camunda/connectors#3632]
__Is your feature request related to a problem? Please describe.__

I manage a process that is triggered through a github command that is used to trigger a webhook to start a process. Sometimes due to the Github API being overloaded it takes some time (5-65 minutes) before I can give feedback to users that the processes has been started, this causes them to issue the command multiple times.

In the end multiple processes are kicked off and only one is typically followed through to completion, leaving process instances that require manual cleanup.

__Describe the solution you'd like__

I would like to be able to deduplicate the incoming webhooks, ensuring only a single process instance is started for each combination of identifiers in the payload of the incomming webhook call.

__Describe alternatives you've considered__

I don't see many alternatives outside of complex mechanisms to interact with the Camunda API's inside the process to do the deduplication. This would add a lot of complexitiy and possibilities for failure inside the process.

__Additional context__

**Comment by sbuettner** [comment]
@jjettenCamunda You can use the `messageId` available for Start Message event based inbound Connectors to enable deduplication. The `messageId` expression can extract some unique identifier from your payload and pass it over to zeebe for idempotency handling in the message buffer: https://docs.camunda.io/docs/next/components/concepts/messages/#message-uniqueness

**Comment by sbuettner** [comment]
Closing this as discussed on slack: https://camunda.slack.com/archives/C02JLRNQQ05/p1731426455214779?thread_ts=1731320781.401299&cid=C02JLRNQQ05
