### ISSUE TITLE
[Rabbit Mq connector] user can not add FEEL expression into the URL field

### ISSUE THREAD

**Issue by mathias-vandaele** [camunda/connectors#3731]
__Describe the Bug__

We can not add a FEEL expression for the url field in Rabbit MQ inbound connector

![image](https://github.com/user-attachments/assets/70b39022-8dc0-4d07-9ac0-cbfe5306513f)

**Comment by sbuettner** [comment]
Discussed in grooming and closing it as FEEL expression support was requested to use it for process variables which are not available for inbound connectors.
