### ISSUE TITLE
Inbound Connectors Not Working on SNAPSHOT Generation

### ISSUE THREAD

**Issue by slolatte** [camunda/connectors#3785]
__Describe the Bug__

When I deploy an inbound connector when using a SNAPSHOT cluster generation on INT, I am getting an 'Webhook not active in any cluster error'. See image below:
<img width="1489" alt="Screenshot 2024-12-12 at 15 04 10" src="https://github.com/user-attachments/assets/87addc12-0fc8-4675-ab94-ac873a22be7a" />

__Steps to Reproduce__

1. On INT create a cluster using the generation 'Cross Component Test Suite'
2. Create a simple diagram with a start event webhook connector and an end event
3. Deploy this process
4. In the webhook tab observe the error

__Expected Behavior__

The inbound connectors should be functioning properly

__Environment__

- OS: [e.g. Windows 7]
- Library version: [e.g. 2.0.0]
- Camunda version: [e.g. 8.0.4 (self-managed)]

**Comment by sbuettner** [comment]
@slolatte Is this still an issue? Asking as @chillleader reported that the issue has been resolved already.

**Comment by sbuettner** [comment]
Closing this for now as we havent received feedback. Feel free to open it again @slolatte if its still persists.
