### ISSUE TITLE
Replace gson with jackson for json mapping

### ISSUE THREAD

**Issue by sbuettner** [camunda/connectors#485]
__What should we do?__

Some connectors use `gson` for dealing with `json` and one connector `microsoft-teams` uses the `jackson` library for that purpose. We should strive for using only one library for dealing with `json` and as `jackson` is the default choice in `spring` we should go for that one.

* Replace `gson` in all connectors with `jackson`
* Remove the gson dependency from the bundle.

__Why should we do it?__

Different `json` libaries and their respective configuration create additional complexity that we can mitigate by using only one library for that purpose.

**Comment by igpetrov** [comment]
Taking over
