### ISSUE TITLE
Cache proxy credentials

### ISSUE THREAD

**Issue by sbuettner** [camunda/connectors#645]
The `ProxyOAuthHelper` in the `connectors-common-library` creates new credentials for every invocation. This leads to a lot of token creations which can cause API limits to exceed. A caching helper should prevent the creation of new credentials as existing ones can be re-used as long as they are still valid.

- [ ] Add an in-memory caching layer for client code relying on the `ProxyOAuthHelper`. The caching can happen outside of the helper if this leads to a cleaner separation of concerns.
- [ ] Cache credentials with a TTL based on the credential expiration time.

**Comment by bastiankoerber** [comment]
@sbuettner is this related to the m2m token?

To get a better understanding, can you answer the following question:
Why should we  do it? What is the pain we want to solve?
What is the benefit to do it (Value Proposition)? 
What is the user impact?
