### ISSUE TITLE
Support standard http proxy concept for the http outbound connector

### ISSUE THREAD

**Issue by sbuettner** [camunda/connectors#810]
__Is your feature request related to a problem? Please describe.__

The current proxy approach requires the proxy to be a compatible version of the http outbound connector. A general support for http proxies could be beneficial for self-managed and SaaS customers that want to control the way outgoing http requests are handled. 

__Describe the solution you'd like__

Investigate and implemented support for http proxies with our http outbound connector implementation.

### Serverless Cloud Function (existing solution)
* Comes with the cold start problem (~ 900ms)
* Simple to manage (serverless and scalable)
* Supports mTLS

### Custom Proxy Service
* Custom proxy implementation but running as a service
* Lower delay as no startup-required
* Could be built using cloud run (easy scaling)
* Supports mTLS
* Would work for self-managed

### Classic HTTP Proxy
* Would require a custom setup to work with mTLS (restarts)
* No custom development needed for basic functionality
* Easy to manage (ha-proxy, nginx traefik, docker image for example)
* Caching of oauth tokens could still live in the runtime

## Deployments models
There are three different deployment models to consider
* Proxy function for all customers in case of a cloud function
* Proxy function per customer in case of a cloud function
* Proxy service for all customers in case of custom proxy / classic proxy
* Proxy service per customers inside the cluster in case of custom proxy / classic proxy

## Existing proxies to consider
* https://github.com/stripe/smokescreen
* https://github.com/reiz/nginx_proxy

## Decision <a href="#decision" id="decision">#</a>
The connectors team decided to move on with the *Classic HTTP Proxy* approach. We would therefore now ask our SRE team to support us with this initiative:
* The connectors runtime would use the proxy for all outgoing HTTP requests
* Which HTTP proxy to use?  * https://github.com/stripe/smokescreen for example?
* We would prefer to have a proxy per cluster deployment model to avoid a SPOF for all customers in case a proxy is not working
* We would prefer a solution that doesnt need any updates / maintenance from our side as long as there are no new requirements
* mTLS support is out of scope for now

**Comment by MaxTru** [comment]
(Additional context)
Please note that in one recent customer conversation the hybrid setup (Camunda 8 SaaS + Connector-bundle onPrem) was considered more effective to solve their problem with firewalls. See https://jira.camunda.com/browse/SUPPORT-17540?focusedCommentId=294604&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-294604.

**Comment by sbuettner** [comment]
@MaxTru FYI this ticket is also about a possible usage of not executing outbound http calls directly from the runtime itself but proxying them via http in case of existing proxy restrictions in the enterprise use-case. 

As we currently only support a custom cloud function we are investigating whether a "classical" proxy approach would work as well to avoid the custom development and maintenance of a proxy cloud function. This would enable SaaS and Self-Managed users to benefit from a proxy approach. Currently its only supported on SaaS via the cloud function.

**Comment by sbuettner** [comment]
As discussed in our meeting here are the problems that we would like to solve with this initiative:
* The connectors team would like to get rid of the custom cloud function as its based on a custom connector runtime that needs to be maintained 
* The proxy should not introduce any additional extra latency (like cold starts)
* The proxy should not require any additional authentication (currently required for the cloud function) and should be accessible from a cluster running the connectors runtime
* An established, already existing proxy service is preferred to not maintain any custom proxy code
* mTLS is out of scope for this standard proxy approach as it might require a custom setup for managing customer certificates 

FYI @multani @than-pet

**Comment by multani** [comment]
@sbuettner Last time we discussed back in July, you also mentioned that it was important for the Connectors Bundle to integrate with existing proxies that already exist on-premise for self-managed deployments.

Is it still a requirement for this issue or not?

**Comment by sbuettner** [comment]
@multani Yes, thanks for mentioning that. We expect that a "standard" http proxy approach would enable self-managed customers as they would be able to configure the proxy config themselves similar how we would do it in our SaaS runtime.

**Comment by xevien96** [comment]
A possible fix for this has been provided by a customer that is currently building their own connectors bundle to use the http connectors in their setup with a proxy.

Code provided here: https://jira.camunda.com/browse/SUPPORT-21013

**Comment by sbuettner** [comment]
Handled by the SRE team in https://github.com/camunda-cloud/team-sre/issues/604
