### ISSUE TITLE
Add mTLS Support

### ISSUE THREAD

**Issue by upgradingdave** [camunda/connectors#842]
__Is your feature request related to a problem? Please describe.__

Customers may want to configure the HTTP REST Connector to communicate over mTLS

__Describe the solution you'd like__

I'm not an expert of mLS, but here are some ideas (Feel free to update!)

The server side certificate validation is already provided via the normal tls infrastructure used all over the web. But, we'd need to provide a way to validate client certificates. 

In SaaS, a customer could configure a Secret representing the client's public certificate. Then, the http rest connector backend could use that to validate client certs.

In SM, the client public cert could be added to JKS. Then, the http rest connector backend could use that to validate client certs.

__Describe alternatives you've considered__

It's currently possible for customers to write their own http rest connector to support mTLS

__Additional context__

- Slack Discussion: https://camunda.slack.com/archives/C02JLRNQQ05/p1688656536293809
- mTLS is mentioned in issue #108
- Nice overview of mTLS: https://www.cloudflare.com/learning/access-management/what-is-mutual-tls/

**Comment by sbuettner** [comment]
We will cover this topic in the future again but its currently not easily doable with the current proxy model.

**Comment by sbuettner** [comment]
Additional evidence: https://camunda.slack.com/archives/C05FVD0AZ2R/p1761833077419299

**Comment by crobbins215** [comment]
See @falko [note](https://camunda.slack.com/archives/C05FVD0AZ2R/p1765554440689649?thread_ts=1761833077.419299&cid=C05FVD0AZ2R) Customer ask for SM only.

Explored implementation [#5742 Enable mTLS support for HTTP REST Connector via system SSL context](https://github.com/camunda/connectors/pull/5742)

**Comment by sbuettner** [comment]
@johnBgood I was looking into this and was wondering: To me it seems like that we will have to create a custom http client instance as the `SSLSocketFactory`  is not a "per-request" configuration. If so, we would need to cache the actual http client object to not create a new one for each request. 

As an alternative we could leverage this library which supports managing multiple identities on a URL basis: https://github.com/Hakky54/ayza#routing-identity-material-to-specific-host

WDYT?

**Comment by johnBgood** [comment]
@sbuettner 
Currently, we create a client per-request anyway, so we could implement the mTLS support without much effort.

As follow-up task, if needed, we could cache our clients; this should be trivial. This is how we do it currently:
```java
    try (var client =
        new ProxyAwareHttpClient(
            new ProxyAwareHttpClient.TimeoutConfiguration(
                request.getConnectionTimeoutInSeconds(), request.getReadTimeoutInSeconds()),
            new ProxyAwareHttpClient.ProxyContext(scheme, host),
            request.isFollowRedirects())) 
```

So clients depend only on a small set of parameters (timeouts, scheme, host...). It would be a great improvement, in general, not even related to mTLS.


I'm a bit concerned with dynamic mTLS config, especially with the connection pool. Some requests might be reused with the wrong certificate. We would need to disable connection sharing or the connection pool entirely.

**Comment by sbuettner** [comment]
We could do both 😄 - Have a single cached one for non-mTLS use-cases and use a dedicated one for the requests that require mTLS.

The library seems to support multiple formats and makes it easy to load and support them. What do you think of integrating it, in the first place on a client-per request basis and caching as a possible second step?

**Comment by sbuettner** [comment]
@crobbins215 Should we create an epic for this issue?

**Comment by crobbins215** [comment]
It is in the https://github.com/camunda/product-hub/issues/3583 epic, or you mean a full pdp just for this one issue?

**Comment by gustavo-camunda** [comment]
Additional evidence: https://jira.camunda.com/browse/SUPPORT-32615

**Comment by sbuettner** [comment]
@crobbins215 A dedicated epic for this issue
