### ISSUE TITLE
Remove nonce field

### ISSUE THREAD

**Issue by igpetrov** [camunda/connectors#849]
⚠️ this is a public ticket, please do not mention Customer, impact details, or any sensitive information.

__Progress__

- [x] Remove and test nonce in SM: https://github.com/camunda/connectors/pull/1010, https://github.com/camunda/connectors/pull/1014
- [ ] Remove and test nonce in SaaS: https://github.com/camunda/web-modeler/pull/5714
__What should we do?__

We need to remove a nonce field introduced in PRs [[1](https://github.com/camunda/web-modeler/pull/5323), [2](https://github.com/camunda/connectors-bundle/pull/848)].

__Why should we do it?__

The `nonce` was introduced in order to mitigate SUP-17567 incident. The reason being, nonce forces to evaluate `configuration: {...}` object first. otherwise we would see `Failed to evaluate FEEL expression error`.

This was a fast but hacky solution which needs to be reverted and tested again as soon as possible in order to not piling hacky code / technical debt.

**Comment by sbuettner** [comment]
@igpetrov Please provide some more context. I assume its about the AWS element templates but would be good to know how urgent this is.

**Comment by igpetrov** [comment]
Hi @sbuettner. I put notes on this ticket. If somebody has spare time, it would be nice to pick this up.
