### ISSUE TITLE
Connectors cannot keep with a high workload and starts to bottleneck

### ISSUE THREAD

**Issue by romansmirnov** [camunda/connectors#893]
A few weeks ago, a prospect was validating our C8 SaaS offering. They were especially interested in orchestrating their services by using REST Connectors. The critical path of their process had 6 REST Connector tasks in a row.

![image](https://github.com/camunda/connectors-bundle/assets/2368139/c3e42eb5-50f6-4700-826c-2c49b6a279ef)

In terms of throughput and latency, they had the following requirements:
* Sustainable throughput: 300 PI per minute
* If there are some special events or offerings, the expected throughput could peak at up to 3,000 PI per minute.
* Latency: Process Instance Execution should be less than 1s (if not even less than 500ms), meaning, a single process instance should complete in less than 1s.
* While validating the product, they tested with a throughput of 250 PI per minute.

According to the test results, the expected latency was not reached. The process instance execution time was growing up to many minutes. Also if they stopped creating new process instances, it still took many minutes to empty the backlog of jobs and process instances. (I don't exactly remember the numbers anymore.)

To rule out, that the prospect's environment does not bottleneck, the following has been checked:
* The REST Connector setting:
  * No authentication configured
  * Just a simple endpoint call.
* The endpoint itself was a "noop". They showed us the metrics for the called endpoint which clearly showed that the endpoint immediately responded (in less than ~1 ms).

To rule out, that the performance issue they observed was caused by our cluster sizing, they tested on different cluster plans, but it always resulted in the same results.

So, we ended up checking the connectors metrics which showed that executing a single "http" job took on average ~250ms. Based on the findings above, it suggests that this time is mostly lost in the connector's runtime itself. At that moment, we haven't done any micro-benchmarks measuring the connector's latency in detail, but when checking the code, the following have been identified as potential bottlenecks (but have not been confirmed further):

1. The connector's runtime runs with the default values, meaning, there is only one worker thread that works on jobs.
2. The HTTP calls are blocking, meaning, the call blocks until it receives the response. Only then it continues to work on the next job. A better approach would be to implement it in a [non-blocking way](https://blog.bernd-ruecker.com/writing-good-workers-for-camunda-cloud-61d322cad862).
3. There is some piece of code that gets per reflection all fields annotated with `@Secrets`. So that any secret placeholder is replaced on-the-fly with actual values before doing the actual call. The replacement can be deep nested, meaning, there is a map which again could contain a map, and so on. But reflection itself adds overhead, especially, when all fields (of the respective call) are anyway annotated with `@Secrets`. Instead, an explicit call to replace the secrets would avoid access via reflection. (Please note: This hasn't been measured, it just looks like a lot of overhead when checking the code. Of course, this observation might be wrong.)
4. Just a side node: With a growing cluster plan, the connector is not set up for scale, i.e., in all cluster plans the connector's runtime is configured the same in terms of resources and everything else.

*Expected behavior*
* Needs further clarification on the expected throughput and latency.
* But still, connectors should be set up in a way that it can handle the workload and does not act as a bottleneck.

**Comment by sbuettner** [comment]
As discussed in the weekly, lets increase the number of threads first (10 as discussed) and continue looking for improvements. 

@romansmirnov All outbound http calls are currently proxied by a cloud function. This might change in the future but it currently adds a delay for every outgoing http call. 

Caching: Authentication is currently not cached. In case of oatuh this will lead to a total of 4 http calls
* 2 for the auth (including proxy)
* 2 for the actual http call (including proxy)

**Comment by sbuettner** [comment]
@romansmirnov Sure, thank you for the input and let us know in case you are facing more performance issues.

**Comment by sbuettner** [comment]
@chillleader might be interesting in case you run into this: https://github.com/camunda-community-hub/spring-zeebe/issues/424
