### ISSUE TITLE
Inbound Kafka connector will not subscribe from subprocess

### ISSUE THREAD

**Issue by eslateBP3** [camunda/connectors#908]
__Describe the Bug__

Kafka inbound connector in a subprocess never tries to subscribe.
Every other inbound Kafka connector in my BPMN attempts to subscribe to its configured topic when the process is deployed. The only one never attempting a subscription is the one in the subprocess.

__Steps to Reproduce__

1. Create a BPMN with an inbound Kafka connector.
2. Deploy BPMN and confirm that the inbound connector subscribes or attempts and fails to subscribe (viewing Connector logs).
3. Copy the connector. Paste it somewhere in the main process and in a subprocess. Alter the configuration so that the activation or correlation parameters are different for each of the connectors.
4. Deploy the modified BPMN.
5. Confirm that the 2nd connector in the main process attempts to subscribe and that the connector in the subprocess does not.

__Expected Behavior__

Inbound Connectors should work in a subprocess.

__Environment__

OS: Mac OS X Ventura 13.4.1 (22F82)
Library version: Connectors 0.20.2
Camunda version: 8.2.4 (self-managed)

**Comment by igpetrov** [comment]
Should be solved by this: https://github.com/camunda/connectors/pull/1136.

Will test kafka separately shortly.

**Comment by igpetrov** [comment]
Fixed and will be included in the next release/patch release.
