### ISSUE TITLE
Kafka inbound: `additionalProperties` does not deserialize JSON and FEEL

### ISSUE THREAD

**Issue by chillleader** [camunda/connectors#983]
__Describe the Bug__

_originally reported in [Slack](https://camunda-platform.slack.com/archives/C0497FR8XML/p1690834531060719)_

Using the latest versions of Camunda Cloud, Connector Runtime, and OOTB Kafka Connectors, I can no longer specify additional properties as JSON.

I’ve been using this to change the security protocol so that I can authenticate to my Kafka broker as my environment does not use the default setting provided by the connector.

I’ve previously set the following in additional properties and seen this succeed:
```
{"security.protocol":"SASL_PLAINTEXT"}
```
When I do that now, I get

```
2023-07-31 15:14:55 java.lang.IllegalArgumentException: Cannot construct instance of `java.util.LinkedHashMap` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('={"security.protocol":"SASL_PLAINTEXT"}')
```

__Expected Behavior__

FEEL expression and (or) JSON entries for this field are deserialized correctly.

__Environment__

- Connectors version: 0.21.4

**Comment by eslateBP3** [comment]
Confirmed that 0.21.3 against Zeebe / Operate 8.2.4 is able to deserialize JSON from the additional properties field.

**Comment by chillleader** [comment]
Should be resolved in the latest snapshot
