### ISSUE TITLE
Webhook: Variable mapping is cleared after updating to V3

### ISSUE THREAD

**Issue by christian-konrad** [camunda/connectors#991]
__Describe the Bug__

I updated the inbound webhook connector on a start event of mine to V3, and by that, the variable mapping was deleted, and undo is not possible.

__Steps to Reproduce__

1. Define inboud webhook variable mapping in version 1
2. Update to V3
3. The variable mapping is gone

https://github.com/camunda/connectors/assets/56470362/43746f76-ea86-49fc-b82d-d1ca2fc5edd1

__Expected Behavior__

The variable mapping should still be there

**Comment by christian-konrad** [comment]
I believe this would not affect many users, since only a hand full are still using V1 of it.

However, I advise to just be careful with future updates, since this is very frustrating.

Users will then think twice to click "update" again in the future, and loose trust

**Comment by bastiankoerber** [comment]
we will not do anything here, since this doesn't affect that many users.
But we will keep it in mind for further updates with breaking changes: https://github.com/bpmn-io/bpmn-js-element-templates/pull/12
